build: false

platform:
  - x64

image:
  - Visual Studio 2017
  - Visual Studio 2015

environment:
  matrix:
    - MINICONDA: C:\\xeus-conda

init:
  - "ECHO %MINICONDA%"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set VCARGUMENT=%PLATFORM%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - echo "%VCVARPATH% %VCARGUMENT%"
  - "%VCVARPATH% %VCARGUMENT%"
  - ps: Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe
  - cmd: C:\Miniconda.exe /S /D=C:\xeus-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Host dependencies
  - conda install python=3.7 # ptvsd is not available on python 3.8 for windows
  - conda install -c conda-forge xeus-python==0.12.4 xtl cmake cppzmq nlohmann_json pybind11 pybind11_json pip robotframework-interpreter==0.7.2 robotframework-lsp=0.14 gtest=1.8.0
  # Build dependencies
  - conda install cmake -c conda-forge
  # Install test dependencies
  - conda install jupyter_kernel_test -c conda-forge
  # Build and install xeus-robot
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=%MINICONDA%\\Library -D XEXTRA_JUPYTER_DATA_DIR=%MINICONDA%\\share\\jupyter -D XROB_BUILD_TESTS=ON -D XEUS_PYTHONHOME_RELPATH=..\\ ..
  - nmake
  - nmake install
  - jupyter kernelspec list

build_script:
  - cd test
  - test_xeus_robot
  - cd ../../test
  - python test_xrobot_kernel.py -vvv
